# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='cost_to_make',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='sale_price',
        ),
    ]
