# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-24 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapi', '0002_auto_20170724_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapi.MenuItem')),
            ],
        ),
    ]
